import Head from 'next/head'
import styles from '@/styles/Index.module.css'
import { Title } from '@/components/title'
import { Profile } from '@/components/profile'
import { Skills } from '@/components/skills'
import { MainProjects } from '@/components/main-projects'
import { OutsourcingProjects } from '@/components/outsourcing-projects'
import { SideProjects } from '@/components/side-projects'
import { ETC } from '@/components/etc'
import { Footer } from '@/components/footer'

export default function Index() {
  return (
    <>
      <Head>
        <title>ㅁㄴㅇㄹ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Title />
        <Profile />
        <Skills />
        <MainProjects />
        <OutsourcingProjects />
        <SideProjects />
        <ETC />
        <Footer />
      </main>
    </>
  )
}
